def categoriesByRound():
   All_Rounds = ["Before & After",
                 "Literature",
                 "Science",
                 "Word Origins",
                 "American History",
                 "State Capitals",
                 "World History",
                 "Business and Industry",
                 "Potpourri",
                 "World Geography"]
   Jeopardy =   ["Sports",
                 "Potpourri",
                 "Animals",
                 "Stupid Answers",
                 "American History",
                 "Science",
                 "State Capitals",
                 "Television",
                 "U.S. Cities",
                 "Pop Music",
                 "Transportation"]
   Double_Jeopardy = ["Opera",
                      "Ballet",
                      "Art",
                      "Shakespeare",
                      "Islands"]
   Final_Jeopardy =  ["U.S. Presidents",
                      "Authors",
                      "World Leaders",
                      "Historic Names",
                      "Famous Americans",
                      "Famous Names",   
                      "Americana",
                      "Organizations"]
   return {"All Rounds" : All_Rounds, "Jeopardy" : Jeopardy, "Double Jeopardy" : Double_Jeopardy, "Final Jeopardy" : Final_Jeopardy}
